"""empty message

Revision ID: 7fd7a97fc065
Revises: 42cd943446cb
Create Date: 2022-09-21 20:31:35.989526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd7a97fc065'
down_revision = '42cd943446cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('genre', sa.String(length=30), nullable=True),
    sa.Column('pages', sa.String(length=30), nullable=True),
    sa.Column('isbn', sa.String(length=150), nullable=True),
    sa.Column('publisher', sa.String(length=150), nullable=True),
    sa.Column('year', sa.String(length=30), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
